# Generated by Django 4.2.5 on 2023-09-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=15)),
                ('event_time', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=10)),
                ('aggregate_trade_id', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('first_trade_id', models.IntegerField()),
                ('last_trade_id', models.IntegerField()),
                ('trade_time', models.BigIntegerField()),
                ('buyer_mm', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SOLUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=15)),
                ('event_time', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=10)),
                ('aggregate_trade_id', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('first_trade_id', models.IntegerField()),
                ('last_trade_id', models.IntegerField()),
                ('trade_time', models.BigIntegerField()),
                ('buyer_mm', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='XRPUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=15)),
                ('event_time', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=10)),
                ('aggregate_trade_id', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('first_trade_id', models.IntegerField()),
                ('last_trade_id', models.IntegerField()),
                ('trade_time', models.BigIntegerField()),
                ('buyer_mm', models.BooleanField()),
            ],
        ),
    ]
