# Generated by Django 4.2.5 on 2023-09-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_trade_stream', '0002_remove_btcusd_symbol_remove_solusd_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.BigIntegerField()),
                ('trade_id', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('buyer_trade_id', models.IntegerField()),
                ('seller_trade_id', models.IntegerField()),
                ('trade_time', models.BigIntegerField()),
                ('buyer_mm', models.BooleanField()),
                ('received_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SOLUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.BigIntegerField()),
                ('trade_id', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('buyer_trade_id', models.IntegerField()),
                ('seller_trade_id', models.IntegerField()),
                ('trade_time', models.BigIntegerField()),
                ('buyer_mm', models.BooleanField()),
                ('received_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XRPUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.BigIntegerField()),
                ('trade_id', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('buyer_trade_id', models.IntegerField()),
                ('seller_trade_id', models.IntegerField()),
                ('trade_time', models.BigIntegerField()),
                ('buyer_mm', models.BooleanField()),
                ('received_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BTCUSD',
        ),
        migrations.DeleteModel(
            name='SOLUSD',
        ),
        migrations.DeleteModel(
            name='XRPUSD',
        ),
    ]
