# Generated by Django 4.2.5 on 2023-09-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_trade_stream', '0003_btcusdt_solusdt_xrpusdt_delete_btcusd_delete_solusd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcusdt',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='btcusdt',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='solusdt',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='solusdt',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='xrpusdt',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='xrpusdt',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
