# Generated by Django 4.2.5 on 2023-09-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_trade_stream', '0004_alter_btcusdt_price_alter_btcusdt_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcusdt',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='solusdt',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='xrpusdt',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
